### ISSUE TITLE
Crash on 1.18.2

### ISSUE THREAD

**Issue by Arthurmeade12** [Deftu/DeftuLib#5]
Same issue as [https://github.com/Deftu/DeftuLib/issues/3](https://github.com/Deftu/DeftuLib/issues/3).

The patch including okio/Buffer was obviously not backported to 1.18.2. I will accept the fact that you may not want to do backports, but if that is not the case, can you include this patch into a 1.18.2 version?

Log: [https://mclo.gs/ZcaU4tP]( https://mclo.gs/ZcaU4tP)

**Comment by Deftu** [comment]
I'll take a look into seeing what I need to change to include a permanent 1.18.2 backport again. I assumed no one was still playing on the version. My bad!

**Comment by Deftu** [comment]
A 1.18.2 version of DeftuLib is now available as of [version 1.8.0](https://modrinth.com/mod/deftulib/version/1.8.0+1.18.2-fabric) and will be supported permanently from now on.
